var num = 123;
var myName = 'Alfred';
var checkStatus = true;
var nullVar = null;
var undefinedVar = undefined;
var whatEver = 'Any variable Type';
var voidVar = null;
console.log(num);
console.log(myName);
console.log(checkStatus);
console.log(nullVar);
console.log(undefinedVar);
console.log(whatEver);
console.log(voidVar);
